# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: tool3/bump@master
        id: bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: 'Github Action'
          email: 'action@github.com'
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Setup
        run: |
          npm install
          npm run lerna:bootstrap
          git reset --hard
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Run checks
        run: |
          npm run checks
          echo "COVERAGE_REPORTS=\"$(ls -dm packages/*/coverage/lcov.info | tr -d ' ')\"" >> $GITHUB_ENV
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{env.COVERAGE_REPORTS}}
      - name: Build
        run: npm run build
      - name: Publish
        run: |
          npm run lerna:version
      - name: Add generated documentation
        run: |
          if [[ -d /docs ]];
          then
            git add docs --force
            git stash
            git checkout docs
            git stash pop --quiet || true
            git checkout --theirs -- docs || true
            git reset
            for PACKAGE in $(ls docs); do (git diff --quiet -- docs/$PACKAGE/latest || git add docs/$PACKAGE) done
            git diff --cached --quiet || (git commit -m "github action: documentation update"; git push)
            git reset --hard
            git checkout master
          fi
      - name: Update readme file
        run: |
          npm run readme
          git diff --quiet -- README.md || git add README.md
          git diff --cached --quiet || (git commit -m "github action: readme file update"; git push)
          git reset --hard
