# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: setup
      - run: |
          npm install
          npm run bootstrap
          git reset --hard
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: checks
      - run: |
          npm run checks
          npm test
      - name: build
      - run: npm run build
      - name: documentation
      - run: npm run docs
      - name: publish
      - run: npm run version
