# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Setup
        run: |
          npm install
          npm run lerna:bootstrap
          git reset --hard
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          VERSION_TYPE="patch"
          [[ $LAST_COMMIT_MESSAGE == *"MIST_MINOR_VERSION"* ]] && VERSION_TYPE="minor"
          [[ $LAST_COMMIT_MESSAGE == *"MIST_MAJOR_VERSION"* ]] && VERSION_TYPE="major"
      - name: Run checks
        run: |
          npm run checks
          npm run test:ci
          git add docs/*/badges --force
          git stash
          git fetch
          git checkout docs
          git stash pop --quiet || true
          git checkout --theirs -- docs || true
          git add docs/*/badges
          git diff --cached --quiet -- docs/*/badges || (git commit -m "github action: coverage badges update"; git push)
          git checkout master
      - name: Build
        run: npm run build
      - name: Publish
        run: npm version $VERSION_TYPE
      - name: Generate documentation
        run: |
          npm run docs
          git add docs --force
          git stash
          git checkout docs
          git stash pop --quiet || true
          git checkout --theirs -- docs || true
          git reset
          for PACKAGE in $(ls docs); do (git diff --quiet -- docs/$PACKAGE/latest || git add docs/$PACKAGE) done
          git diff --cached --quiet || (git commit -m "github action: documentation update"; git push)
          git reset --hard
          git checkout master
      - name: Update readme file
        run: |
          npm run readme
          git diff --quiet -- README.md || git add README.md
          git diff --cached --quiet || (git commit -m "github action: readme file update"; git push)
          git reset --hard
